### ISSUE TITLE
Joining a subject

### ISSUE THREAD

**Issue by majzabukovnik** [zanurban/spletna-ucilnica#32]
@zanurban Is it a feature that student can only join subjects that have been chosen for certain student by the admin? If that is the case please fix the display of avalible subjects because currently all of the subjects are listed.

**Comment by zanskorja** [comment]
@majzabukovnik Student can join any subject they want

**Comment by majzabukovnik** [comment]
It does not work

**Comment by zanskorja** [comment]
It does, i will show you in the school
