### ISSUE TITLE
Download of assigments does not work

### ISSUE THREAD

**Issue by zanskorja** [zanurban/spletna-ucilnica#41]
Class "ZipArchive" not found

**Comment by majzabukovnik** [comment]
Locate your php.ini file. This file is typically located in your PHP installation directory. If you're using XAMPP, it can be found in the php directory (e.g., C:\xampp\php\php.ini).

Open php.ini in a text editor.

Search for the following line and remove the semicolon (;) at the beginning if it's there:

python
Copy code
;extension=zip
Change it to:

makefile
Copy code
extension=zip
Save the php.ini file.

Restart your web server or PHP service for the changes to take effect.

**Comment by majzabukovnik** [comment]
@zanurban This is only problem with your computer
